name: CommandBlocker
version: 3.0
main: it.chiarchiaooo.commandblocker.CommandBlocker
api-version: 1.13
authors: [ Chiarchiaooo ]
description: Simple Command Blocking plugin made for Minecraft
softdepend: [PlaceholderAPI]

commands:
  cmdblock:
    description: Main Command

permissions:
  cmdblock.bypass.*:
    description: General bypass permission
  cmdblock.bypass.<command>:
    description: Single command bypass permission
  cmdblock.bypass.<group>:
    description: Group-based command bypass permission
  cmdblock.<command>.command:
    description: Access to a specific commandblocker command